import "./globals.css";
import Header from "@/src/components/Header";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Footer from "@/src/components/Footer";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ian Ona",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <div className="min-h-screen py-8">
          {/* <Header /> */}
          <main>{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
