import Head from 'next/head'
import Hero from "@/src/components/Hero"
import { Metadata } from 'next'

export default function Home() {
  return (
    <div>
      {/* <Head>
        <title>Ian Ona</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Hero />
    </div>
  )
}
